version: '3.4'
services:
  netbox:
    image: netbox:latest-plugins
    pull_policy: never
    ports:
    - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile-Plugins
    volumes:
    - /volume1/docker/netbox/config:/etc/netbox/config:z,ro
    - /volume1/docker/netbox/netbox-media-files:/opt/netbox/netbox/media:z,rw
    - /volume1/docker/netbox/netbox-reports-files:/opt/netbox/netbox/reports:z,rw
    - /volume1/docker/netbox/netbox-scripts-files:/opt/netbox/netbox/scripts:z,rw
    healthcheck:
      retries: 15
  netbox-worker:
    image: netbox:latest-plugins
    pull_policy: never
    volumes:
    - /volume1/docker/netbox:/etc/netbox/config:z,ro
    - /volume1/docker/netbox/netbox-media-files:/opt/netbox/netbox/media:z,rw
    - /volume1/docker/netbox/netbox-reports-files:/opt/netbox/netbox/reports:z,rw
    - /volume1/docker/netbox/netbox-scripts-files:/opt/netbox/netbox/scripts:z,rw
  netbox-housekeeping:
    image: netbox:latest-plugins
    pull_policy: never
    volumes:
    - /volume1/docker/netbox:/etc/netbox/config:z,ro
    - /volume1/docker/netbox/netbox-media-files:/opt/netbox/netbox/media:z,rw
    - /volume1/docker/netbox/netbox-reports-files:/opt/netbox/netbox/reports:z,rw
    - /volume1/docker/netbox/netbox-scripts-files:/opt/netbox/netbox/scripts:z,rw
